validation now created for signup and signin routes
fredie7/sendIT pull request #5
Opened 2020-01-13 13:04 UTC by fredie7

pull request for ft-auth-request-validation

2020-01-14 12:29 UTC, jsamchineme requested changes

2020-01-14 12:29 UTC, jsamchineme commented on routers/auth.js
> +import validate from '../validator';
instead of **validate**, why not name this **validator**

2020-01-14 14:25 UTC, fredie7 commented on routers/auth.js
> +import validate from '../validator';
I've made corrections..Thanks

2020-01-14 16:35 UTC, jsamchineme commented on controllers/auth.js
> +      return res.status(409).json({ error: 'user does not exist' });
The status code here should still be reverted to `401`, cos that's the appropriate value.This is not a conflict.

2020-01-14 16:36 UTC, jsamchineme commented on test/appTest.js
> +// const assert = require('chai').assert;
delete the `test/appTest.js` file

2020-01-15 21:30 UTC, jsamchineme approved these changes

2020-01-15 21:31 UTC, merged