jwt authorizaion
fredie7/sendIT pull request #8
Opened 2020-01-24 09:19 UTC by fredie7

const token = req.headers.authorization 
returns a token but get negated upon authorization but when I incorporated token using jwt.sign(), it worked out but terminal says 'cannot set request header after sent.'

2020-01-24 10:05 UTC, jsamchineme requested changes

2020-01-24 10:05 UTC, jsamchineme commented on controllers/auth.js
> +        res.json({ authData });
The authData is not to be returned in a response. It is passed on to the next middleware, attached to the request object. 
Just before your `next()` statement, do `req.decoded = authData`

2020-01-24 10:05 UTC, jsamchineme commented on routers/auth.js
> +router.post('/signin', signinValidator, verifyUser, signin);
You can't have been hr verifyUser middleware before your signing. You use if for protected routes eg. CreateParcel that requires a valid user's token.

2020-01-27 12:05 UTC, jsamchineme commented on routers/parcel.js
> +router.post('/protected', authController.verifyToken, (req, res) => {
With what you have here, you should be able to test on Postman that the middleware works.
Make a POST request to `api/v1/parcels/protected` providing the token in the authorization header, and see what you get returned. Use both a valid token and an invalid token. A valid token is the one you get after sign-in, untampered. An invalid would be any other bunch characters, or a token that has expired.

2020-01-27 12:05 UTC, jsamchineme commented on app.js
>  const authRoute = require('./routers/auth');
Remove all `require()` statements. replace them with the `import` format.

2020-01-27 12:11 UTC, fredie7 commented on routers/parcel.js
> +router.post('/protected', authController.verifyToken, (req, res) => {
it says unauthhorized

2020-01-27 12:20 UTC, fredie7 commented on app.js
>  const authRoute = require('./routers/auth');
I've fixed those

2020-01-27 17:38 UTC, jsamchineme commented on app.js
>  const authRoute = require('./routers/auth');
fix this too.

2020-01-27 17:39 UTC, jsamchineme commented on app.js
> +const parcelRoutes = require('./routers/parcel');
fix this too

2020-01-27 17:39 UTC, jsamchineme reviewed
Fix the rest of the require statements and we should be good.

2020-01-28 09:19 UTC, merged